### ISSUE TITLE
MQ Prometheus Exporter - ibmmq_queue_depth not found for queue names with /

### ISSUE THREAD

**Issue by TstGitTest** [ibm-messaging/mq-metric-samples#18] opened 2019-08-19 17:26 UTC
Hello,
Here's an issue I am currently experiencing when working with MQ Prometheus Exporter. 

### Brief Description
ibmmq_queue_depth metric is not published by the MQ Prometheus Exporter for the queues having a queue name containing "/" character. 

### Reproducer
- mq-metrics-samples version(s) that are affected by this issue.
9ce9d17c73653d2b03b1ae8586338a9be1de8d22 

- Dockerfile used to run IBM-MQ 9.1.2.0 DEV version and compile the MQ Prometheus Exporter
[Dockerfile.txt](https://github.com/ibm-messaging/mq-metric-samples/files/3516862/Dockerfile.txt)

- Docker run command used to run the container
`docker run --entrypoint "/bin/bash" --env LICENSE=accept --env MQ_DEV=true --env MQ_QMGR_NAME=QM1 --env MQ_APP_PASSWORD=app --env MQ_ADMIN_PASSWORD=admin  --publish 1414:1414 --publish 9157:9157 --publish 9443:9443 --ipc host -it ibm_mq_prometheus:9.1.2.0-dev-build`

- Copy the compiled MQ Prometheus, shell wrapper and configuration into /usr/local/bin/mqgo/
` cd /root/gowork/bin/;  mkdir /usr/local/bin/mqgo; cp mq* /usr/local/bin/mqgo/; cd /usr/local/bin/mqgo/ `

- Update MQ Prometheus Exporter Queue Pattern
` sed -i 's/APP\.\*,MYQ\.\*/\*,\!SYSTEM\.\*,\!AMQ\.\*/g' /usr/local/bin/mqgo/mq_prometheus.sh`
   Queue pattern should look like: 
`queues="*,!SYSTEM.*,!AMQ.*"`

- Udpate MQ Configuration to include a Queue with name containing a '/' character 
Modify i.e. /etc/mqm/10-dev.mqsc.tpl by adding 
`DEFINE QLOCAL('DEV/QUEUE/3') REPLACE`

- Start the Queue Manager
`su mqm; runmqdevserver;`

    If asked, re-run it as root (probably for password setup), then remove /run/runmqserver/tls/ and re-run it as mqm. 

- Start MQ Prometheus Exporter 
`./mq_prometheus.sh QM1 &`

- Look  for the published metrics :
```
# HELP ibmmq_queue_attribute_max_depth Queue Max Depth
# TYPE ibmmq_queue_attribute_max_depth gauge
ibmmq_queue_attribute_max_depth{platform="UNIX",qmgr="QM1",queue="DEV.DEAD.LETTER.QUEUE",usage="NORMAL"} 5000
ibmmq_queue_attribute_max_depth{platform="UNIX",qmgr="QM1",queue="DEV.QUEUE.1",usage="NORMAL"} 5000
ibmmq_queue_attribute_max_depth{platform="UNIX",qmgr="QM1",queue="DEV.QUEUE.2",usage="NORMAL"} 5000
ibmmq_queue_attribute_max_depth{platform="UNIX",qmgr="QM1",queue="DEV.QUEUE.3",usage="NORMAL"} 5000
ibmmq_queue_attribute_max_depth{platform="UNIX",qmgr="QM1",queue="DEV/QUEUE/3",usage="NORMAL"} 5000
# HELP ibmmq_queue_depth Queue depth
# TYPE ibmmq_queue_depth gauge
ibmmq_queue_depth{platform="UNIX",qmgr="QM1",queue="DEV.DEAD.LETTER.QUEUE",usage="NORMAL"} 0
ibmmq_queue_depth{platform="UNIX",qmgr="QM1",queue="DEV.QUEUE.1",usage="NORMAL"} 0
ibmmq_queue_depth{platform="UNIX",qmgr="QM1",queue="DEV.QUEUE.2",usage="NORMAL"} 0
ibmmq_queue_depth{platform="UNIX",qmgr="QM1",queue="DEV.QUEUE.3",usage="NORMAL"} 0
```
    
As you can see **ibmmq_queue_depth** metric is not available for DEV/QUEUE/3 queue.

To me it seems as there is an issue during the queue discovery; I'm not really experienced in GO so I did not try my chance with the debugger. 

Thanks a lot in advance

**Comment by ibmmqmet** [comment] 2019-08-20 09:33
This is actually a problem with the way that the queue manager recognises and publishes the resource stats. There's nothing that can be done currently in this Prometheus package to solve it. All I can do right now would be to put something in the README to warn about it.

Objects with '/' in the name are not being processed correctly - basically the '/' is being taken as the separator in a topic tree.

You can see the same thing if you run
```
amqsrua -c STATQ -t GET -o DEV/QUEUE/1
```
which will timeout with no publications received. 

Because it's reproducible outside of this package, you could try opening a service request/PMR against MQ to see if it can be fixed via APAR in the future.

**Comment by ibmmqmet** [comment] 2019-08-20 13:44
I've added a warning message for this situation, in v4.1.0 of the mq-golang repository

**Comment by ibmmqmet** [comment] 2019-08-21 08:53
Closing as there's nothing more to be done here. If an APAR is accepted, or the qmgr is modified in future, I'll add a comment then.

**Closed by ibmmqmet** 2019-08-21 08:53 UTC
